language: java
jdk:
  - oraclejdk8

dist: trusty

install: skip

script: skip

deploy:
  provider: script
  script: cp .travis-maven-settings.xml $HOME/.m2/settings.xml && mvn -DperformRelease=true deploy
  on:
    all_branches: true